deployment:
  tasks:
    - export DEPLOYPATH=/home/kemg7663/public_html
    - /bin/mkdir -p $DEPLOYPATH
    - /usr/bin/rsync -a --delete --exclude '.git' --exclude '.env' --exclude 'storage' --exclude 'bootstrap/cache' ./ $DEPLOYPATH
